config/routes.rb
Rails.application.routes.draw do
  
  resources :access_requests

  root 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions", profiles: "users/profiles"}
  
  get 'posts/list' => 'posts#list'
  resources :posts
  
  resources :comments, except: [:new]

  resources :settings
  

  get 'articles/:articleid' => 'articles#show', as: :show_article
  get 'articles' => 'articles#index', as: :articles
  
  get 'biography' => 'pages#biography'
  get 'bibliography' => 'pages#bibliography' 

  get "comments/new/:itemid(/:pid)" => 'comments#new', as: :new_comment
  get "comments/list/:itemid(/:pid)" => 'comments#list', as: :list_comments
  
  get "index" => 'indices/indices#index'
  
  get "index/names/list(/:category)" => 'indices/names#list'
  get "index/names/show(/:nameid)" => 'indices/names#show'
  get "index/names/categories" => 'indices/names#categories'
  
  get "index/titles/list(/:category)" => 'indices/titles#list'
  get "index/titles/show(/:titleid)" => 'indices/titles#show'
  get "index/titles/categories" => 'indices/titles#categories'

  get "index/quotes/list(/:category)" => 'indices/quotes#list'
  get "index/quotes/show(/:quoteid)" => 'indices/quotes#show'
  get "index/quotes/categories" => 'indices/quotes#categories'

scope 'paragraphs' do
  get 'index' => 'paragraphs#index'
  get 'info' => 'paragraphs#info'
  get 'plaintext' => 'paragraphs#plaintext'
  get 'show2' => 'paragraphs#show2'

  get 'collation/:itemid/:pid' => 'paragraphs#collation', as: :paragraphs_collation
  get 'xml/:itemid/:pid(/:msslug)' => 'paragraphs#xml', as: :paragraphs_xml
  get 'json/:itemid/:pid(/:msslug)' => 'paragraphs#json', as: :paragraphs_json
  get 'variants/:itemid/:pid' => 'paragraphs#variants', as: :paragraphs_variants
  get 'notes/:itemid/:pid' => 'paragraphs#notes', as: :paragraphs_notes
  
  get ':itemid/:pid(/:msslug)' => 'paragraphs#show'
end
  
  get 'paragraphexemplar/json/:itemid/:pid' => 'paragraphexemplar#json'

  get 'permissions' => 'pages#permissions'
  
  get 'search' => 'search#show', as: :show_search

scope "text" do
  get '' => 'text#index'
  get 'draft_permissions/:itemid' => 'text#draft_permissions'
  get 'questions' => 'text#questions'
  get 'info/:itemid' => 'text#info'
  get 'status/:itemid' => 'text#status'
  get 'toc/:itemid(:/msslug)' => 'text#toc'
  get 'xml/:itemid(:/msslug)' => 'text#xml'
  get ':itemid(/:msslug)' => 'text#show', as: :show_text
end 

  get 'paragraphimage/showfoliozoom/:msslug/:canvas_id' => 'paragraphimage#showfoliozoom'
  get 'paragraphimage/showzoom/:itemid/:msslug/:pid' => 'paragraphimage#showzoom'
  get 'paragraphimage/:itemid/:msslug/:pid' => 'paragraphimage#show'

  
  get 'users/profiles/:id' => 'users/profiles#show', as: :users_profile
  delete 'users/profiles/:id' => 'users/profiles#destroy', as: :destroy_users_profile
  put 'users/profiles/:id' => 'users/profiles#update', as: :update_users_profile
  post 'users/profiles' => 'users/profiles#create', as: :create_users_profile
  get 'users/profiles' => 'users/profiles#index'

  get 'accesspoints/:commentaryid/:itemid' => 'access_points#show', as: :access_point
  post 'accesspoints/:id' => 'access_points#create', as: :create_access_point
  delete 'accesspoints/:id' => 'access_points#destroy', as: :delete_access_point
  

  

  

  

end

app/controllers/text_controller.rb
class TextController < ApplicationController
	include TextMethods
	
  def index
		commentaryid = @config.commentaryid
		url =  "<http://scta.info/text/#{commentaryid}/commentary>" 
		@results = Lbp::Query.new().collection_query(url)
	end
	def questions
		commentaryid = @config.commentaryid
		url =  "<http://scta.info/text/#{commentaryid}/commentary>" 
		@results = Lbp::Query.new().collection_query(url)
	end

	def info
		item = get_item(params)
		check_permission(item)
		@title = item.title
		@itemid = item.fs
		commentaryid = @config.commentaryid
		url = "http://scta.info/text/#{commentaryid}/item/#{params[:itemid]}"
		query = Lbp::Query.new
		@name_results = query.names(url)
		@quote_results = query.quotes(url)
		
	end

	def status
		commentaryid = @config.commentaryid
		url = "<http://scta.info/text/#{commentaryid}/item/#{params[:itemid]}>"
		results = Lbp::Query.new.item_query(url)
		@itemid = params[:itemid]
		@results = results.order_by(:transcript_type)
		if @results.count == 0
			flash.clear
		end
	end

	def show
		if params.has_key?(:search)
			flash.now[:notice] = "Search results for instances of #{params[:searchid]} (#{params[:search]}) are highlighted in yellow below." 
		end
		
		item = get_item(params)
		check_permission(item); return if performed?
		check_transcript_existence(item, params); return if performed?

		if item.status == "In Progress" || item.status == "draft"
			flash.now[:alert] = "Please remember: the status of this text is draft. You have been granted access through the generosity of the editor. Please use the comments to help make suggestions or corrections."
		end
		
		@title = item.title
		#remove @fs after check for use. use itemid instead
		@fs = item.fs
		@itemid = item.fs
		@next_itemid = if item.next != nil then item.next.split("/").last else nil end
		@previous_itemid = if item.previous != nil then item.previous.split("/").last else nil end

		transcript = get_transcript(item, params)
		
		#always remember single quotes for paramater value
		#specify if global image setting is true or false
		xslt_param_array = ["default-ms-image", if default_wit(params) == "critical" then @config.default_ms_image else "'#{default_wit(params)}'" end, 
				"default-msslug", "'#{default_wit(params)}'", 
				"show-images", "'#{@config.images.to_s}'"]
		
		@transform = transcript.transform_main_view(xslt_param_array)

	end
	
	def xml
		item = get_item(params)
		check_permission(item)

		transcript = get_transcript(item, params)
		@nokogiri = transcript.nokogiri
	end

	def toc 
		item = get_item(params)
		check_permission(item)

		transcript = get_transcript(item, params)
		@toc = transcript.transform_toc
		render :layout => false
	end

	def draft_permissions
		
	end

	private

end

app/helpers/text_helper.rb
module TextHelper
end

app/views/text/_text_nav_bar.html.erb
<nav id="lbp-text-tool-bar" class="navbar navbar-default navbar-fixed-bottom" style="background-color: <%= @config.light_color %>;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#lbp-text-tool-bar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Text Tool Bar</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="lbp-text-tool-bar-collapse" class="collapse navbar-collapse" >
      <ul class="nav navbar-nav">
        <% unless params.has_key?(:msslug) && params[:msslug] != "critical" %>
          <li><a class="js-show-outline" data-itemid="<%= @itemid %>">Text Outline</a></li>
        <% end %>
        <% if @previous_itemid != nil  %>
          <li><%= link_to "Previous", show_text_path(@previous_itemid, params[:msslug]) %></li> 
        <% end %>
        <% if @next_itemid != nil %>
          <li><%= link_to "Next", show_text_path(@next_itemid, params[:msslug]) %></li> 
        <% end %>
          <li><a href="/text/status/<%= params[:itemid] %>">Available Transcriptions</a></li>
        
        
          
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Text Tools <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#" class="js-show-item-xml" data-itemid="<%= @itemid %>">XML</a></li>
            <li class="divider"></li>
            <li><a href="#" class="js-show-item-info" data-itemid="<%= @itemid %>">Text Info/Stats</a></li>
            
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/text/draft_permissions.html.erb
<div id="draftview" class="container">
		<h3>This text is currently a private draft</h3>
		<p>Depending on the state of a transcriptions, editors will often designate their text as a "draft". This means that, while an edition or transcription, has been started it is not yet ready to be viewed by the public. Often an editor will allow and interested reader access to the text, with the understanding that the text is a work in progress.</p>
		<% if !user_signed_in? %>
			<p>To view this text you will need to first create a user account. Then you can return and request permission.</p>
		<% else %>
			<h3> To request draft permissions for this text, please tell the editor a little about yourself and your interest in this text. </h3>
			<%= form_for(:access_request, url: access_requests_path, method: :post) do |f| %>
	 			<div class="field">
	 			<%= f.hidden_field :user_id, :value => current_user.id %>
			  <%= f.hidden_field :itemid, value: params[:itemid] %>
			  <%= f.hidden_field :commentaryid, value: @config.commentaryid %>
			  </div>
			  <div class="field">
			    <%= f.text_area :note, :class => 'ckeditor' %>
			  </div>
			  <div class="actions">
			    <%= f.submit %>
			  </div>
			<% end %>
		<% end %>
</div>

app/views/text/index.html.erb
<div class="container">
  <h1>Table of Contents</h1>

  <div id="lbp-toc-container" class="container">
    <div class="row">
      <div class="col-xs-3 col-md-4">
        <h3>Items</h3>
          <div id="lbp-toc-sidebar">
            <ul class="list-group">
      	      <% @results.each do |result| %>
        	      <% link = "text/" + result[:item].to_s.split('/').last %>
        	      <li class="list-group-item">
        	      	<span class="lbp-item-name"><% if result[:status] != "Not Started" %>
        	      		<%=  link_to result[:title], link %></span></br>
                    <span class="small"><%= link_to "Outline", "#", :class => "js-show-toc", "data-itemid" => result[:item].to_s.split("/").last %></span>
                    
        	      	<% else %>
        	      		<%= result[:title] %>
        					<% end %>
        				</li> 
  	         <% end %>
      	   </ul>
         </div>
      </div>
      <div id="lbp-toc-mainwindow">
        <h3>Outline</h3>
        <div id="lbp-toc-window" class="col-xs-9 col-md-8">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/text/info.html.erb
<div id="lbp-info-container" class="container">
	<h1>Text Info/Stats for <%= @title %></h1>
	<div class="row">
		<div class="col-md-3">
			<div class="panel panel-default">
			  <div class="panel-heading">
			  	<h3 class="panel-title">Mentions</h3>
			  </div>
			  <div class="panel-body">
			    <table class="table table-striped table-hover">
			    	<% @name_results.each do |result| %>
			    	<tr>
			    		<td><%= link_to result[:nameTitle].to_s, result[:name].to_s, target: "_blank" %></td>
			    		
			    	</tr>
			    	<% end %>
			    </table>
			  </div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-default">
				<div class="panel-heading">
				  	<h3 class="panel-title">Quotations Used</h3>
				  </div>
				  <div class="panel-body">
				    <table class="table table-striped table-hover">
				    	<% @quote_results.each do |result| %>
				    	<tr>
				    		<td><%= result[:quoteText].to_s %></td>
				    		<td><%= link_to result[:quoteCitation].to_s, result[:quote].to_s, target: "_blank" %></td>

				    	</tr>
				    	<% end %>
				    </table>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

	

		

app/views/text/questions.html.erb
<style type="text/css">
  .status{display: none;}
  .itemLink:hover .status{display: inline;}
</style>
<div>
  <h1>Question List</h1>
</div>
<div id="lbp-question-container" class="container">
  <table class="table table-striped table-hover">
    <% @results.each do |result| %>
    <% link = "/text/" + result[:item].to_s.split('/').last %>
    <tr>
      <td><%= unless result[:status] == "Not Started" then link_to result[:title], link else result[:title]  end %></td>
      <td><%= unless result[:status] == "Not Started" || result[:questiontitle] == nil  then link_to result[:questiontitle], link else result[:questiontitle]  end %></td>
      <td><%= result[:status] %></td>
    </tr>

        
    <% end %>
  </table>
</div>

app/views/text/show.html.erb
<%= render "text_nav_bar" %>
<% if params[:search] != nil %>
	<div id="lbp-text-body" class="container" data-search="<%= params[:search] %>" data-searchid="<%= params[:searchid] %>">
<% else %>
	<div id="lbp-text-body" class="container">
<% end %>
	<%= raw(@transform) %>
</div>
<!-- side window -->
<div id="lbp-side-window" style="background-color: <%= @config.light_color %>;">
	<nav id="lbp-bottom-window-nav-bar">
		<div class="container-fluid">
			<ul class="nav navbar-nav">
				<li><a class="js-close-side-window">Close</span></a></li>
				<li id="lbp-min-side-window"><a class="js-minimize-side-window">Min</span></a></li> 
				<li id="lbp-max-side-window"><a class="js-maximize-side-window">Max</span></a></li> 
			</ul>
		</div>
	</nav>
	<div id="lbp-side-window-container" style="">
	</div>
</div>
<!-- bottom window -->
<div id="lbp-bottom-window" style="background-color: <%= @config.dark_color %>;">
	<nav id="lbp-bottom-window-nav-bar">
		<div class="container-fluid">
			<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#lbp-bottom-window-navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>
			<div class="collapse navbar-collapse" id="lbp-bottom-window-navbar-collapse">
	    	<ul class="nav navbar-nav">
					<li>
						<a class="js-expand-para-comment">Max
							<span class="dropup">
								<span class="caret"></span>
							</span>
						</a>
					</li> 
					<li><a class="js-halfsize-para-comment">50%</a></li>
					<li><a class="js-minimize-para-comment">Min<span class="caret"></span></a></li> 
					<li><a class="js-close-para-comment">Close</span></a></li>
				</ul>
			</div>
		</div>	
	</nav>
	<div id="lbp-bottom-window-container" class="container">
	</div>
</div>	

app/views/text/status.html.erb
<div id="lbp-item-status-container" class="container">
  <% unless @results.count ==  0 %>
    <h3>Available transcriptions for: <%= @results.first[:item_title] %></h3>
    <table class="table table-striped table-hover">

      <% @results.each do |result|    
        slug = result[:transcript].to_s.split("/").last.split("_").first
        type = result[:transcript_type]
        status = result[:transcript_status]
        if type == "critical" || type == "Critical"
          link = "/text/#{@itemid}"
        else
          link = "/text/#{@itemid}/#{slug}"
        end
        %>
          <tr>
            <td><%= link_to result[:transcript_title].to_s, link %></td>
            <td><%= "type: #{type}" %></td>
            <td><%= "status: #{status}" %></td>
          </tr>
      <% end %>
    </table>
  <% else %>
    <div style="text-align: center; height: 400px; margin-top: 100px">
      <h4>Sorry this text has not been started. <%= link_to "Return to Table of Contents", text_path %></h4>
    </div>
  <% end %>
</div>

app/views/text/toc.html.erb
<div id="lbp-toc-container">
<%= raw(@toc) %>
</div>

app/views/text/xml.html.erb
<div id="lbp-xml-container">
<script type="text/javascript">
$(document).ready(function(){
	$("pre.xmlCode").snippet("xml", {style: "acid"});
});
</script>

<pre id="lbp-xml" class="xmlCode"><%= @nokogiri %></pre>
</div>