config/routes.rb
Rails.application.routes.draw do
  
  resources :access_requests

  root 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions", profiles: "users/profiles"}
  
  get 'posts/list' => 'posts#list'
  resources :posts
  
  resources :comments, except: [:new]

  resources :settings
  

  get 'articles/:articleid' => 'articles#show', as: :show_article
  get 'articles' => 'articles#index', as: :articles
  
  get 'biography' => 'pages#biography'
  get 'bibliography' => 'pages#bibliography' 

  get "comments/new/:itemid(/:pid)" => 'comments#new', as: :new_comment
  get "comments/list/:itemid(/:pid)" => 'comments#list', as: :list_comments
  
  get "index" => 'indices/indices#index'
  
  get "index/names/list(/:category)" => 'indices/names#list'
  get "index/names/show(/:nameid)" => 'indices/names#show'
  get "index/names/categories" => 'indices/names#categories'
  
  get "index/titles/list(/:category)" => 'indices/titles#list'
  get "index/titles/show(/:titleid)" => 'indices/titles#show'
  get "index/titles/categories" => 'indices/titles#categories'

  get "index/quotes/list(/:category)" => 'indices/quotes#list'
  get "index/quotes/show(/:quoteid)" => 'indices/quotes#show'
  get "index/quotes/categories" => 'indices/quotes#categories'

scope 'paragraphs' do
  get 'index' => 'paragraphs#index'
  get 'info' => 'paragraphs#info'
  get 'plaintext' => 'paragraphs#plaintext'
  get 'show2' => 'paragraphs#show2'

  get 'collation/:itemid/:pid' => 'paragraphs#collation', as: :paragraphs_collation
  get 'xml/:itemid/:pid(/:msslug)' => 'paragraphs#xml', as: :paragraphs_xml
  get 'json/:itemid/:pid(/:msslug)' => 'paragraphs#json', as: :paragraphs_json
  get 'variants/:itemid/:pid' => 'paragraphs#variants', as: :paragraphs_variants
  get 'notes/:itemid/:pid' => 'paragraphs#notes', as: :paragraphs_notes
  
  get ':itemid/:pid(/:msslug)' => 'paragraphs#show'
end
  
  get 'paragraphexemplar/json/:itemid/:pid' => 'paragraphexemplar#json'

  get 'permissions' => 'pages#permissions'
  
  get 'search' => 'search#show', as: :show_search

scope "text" do
  get '' => 'text#index'
  get 'draft_permissions/:itemid' => 'text#draft_permissions'
  get 'questions' => 'text#questions'
  get 'info/:itemid' => 'text#info'
  get 'status/:itemid' => 'text#status'
  get 'toc/:itemid(:/msslug)' => 'text#toc'
  get 'xml/:itemid(:/msslug)' => 'text#xml'
  get ':itemid(/:msslug)' => 'text#show', as: :show_text
end 

  get 'paragraphimage/showfoliozoom/:msslug/:canvas_id' => 'paragraphimage#showfoliozoom'
  get 'paragraphimage/showzoom/:itemid/:msslug/:pid' => 'paragraphimage#showzoom'
  get 'paragraphimage/:itemid/:msslug/:pid' => 'paragraphimage#show'

  
  get 'users/profiles/:id' => 'users/profiles#show', as: :users_profile
  delete 'users/profiles/:id' => 'users/profiles#destroy', as: :destroy_users_profile
  put 'users/profiles/:id' => 'users/profiles#update', as: :update_users_profile
  post 'users/profiles' => 'users/profiles#create', as: :create_users_profile
  get 'users/profiles' => 'users/profiles#index'

  get 'accesspoints/:commentaryid/:itemid' => 'access_points#show', as: :access_point
  post 'accesspoints/:id' => 'access_points#create', as: :create_access_point
  delete 'accesspoints/:id' => 'access_points#destroy', as: :delete_access_point
  

  

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  
	enum role: [:admin, :editor, :draft_img_reader, :draft_reader, :public_reader]
	has_many :comments, dependent: :destroy
	has_many :posts, dependent: :destroy
  has_many :access_requests, dependent: :destroy
	has_and_belongs_to_many :access_points

  after_initialize :set_default_role, :if => :new_record?
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def set_default_role
  	self.role ||= :public_reader
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
	before_filter :authenticate_user!
  

	def index
		#unless current_user.admin?
		 #	redirect_to "/permissions", :alert => "Access denied."
    #end
    @users = User.all
    @profile = User.new
    authorize @profile

	end
	def show
		@user = User.find(params[:id])
		@profile = @user
		#not that user in the authorize method is actually the second arg
		#corresponding to the @profile arg in the pundit policy
		authorize @profile
  end
  def create
  	@profile = User.new(profile_params)
    authorize @profile
    if @profile.save
      redirect_to users_profiles_path, :notice => "Profile successfully added"
    end
  end
  def update

  	@profile = User.find(params[:id])
    authorize @profile
    if @profile.update(profile_params)
			redirect_to users_profile_path(@profile), :notice => "Profile successfully update"
		end
  end
  def destroy 

  	@profile = User.find(params[:id])
    authorize @profile
    if @profile.destroy
			redirect_to users_profiles_path, :notice => "Profile successfully deleted"
		end
  end
  

  private 
	  def profile_params
	    params.require(:profile).permit(:email, :password, :role)
	  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/profiles/index.html.erb
<% if current_user.admin? %>
<div class="container">
	<h1>Users</h1>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<td>Email</td>
				<td>Role</td>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= link_to user.email, users_profile_path(user) %></td>
					<td><%= user.role %></td>
					<td><%= user.created_at %></td>
					
					<td><%= link_to "Destroy", destroy_users_profile_path(user), method: :delete %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="container">
	<p>As admin, you can create a new user </p>
	<%= form_for(:profile, url: :create_users_profile) do |f| %>
	  <div class="field">
	    <%= f.label :email %><br />
	    <%= f.email_field :email, autofocus: true %>
	  </div>
		<div class="field">
	    <%= f.label :password %>
	    <br />
	    <%= f.password_field :password, autocomplete: "off" %>
	  </div>
	  <div class="role">
	    <%= f.label :role %>
	    <br />
	    <%= f.text_field :role, autocomplete: "off" %>
	  </div>
		<div class="actions">
			<br />
	    <%= f.submit "Create User" %>
	  </div>
	<% end %>
</div>
<% else %>
<p>You are not authorized to view the profiles list</p>
<% end %>

		

app/views/users/profiles/show.html.erb
<div class="container center">
	<div>
		<h1><%= @user.email %></h1>
		<p><%= @user.role %></p>
		<p><%= @user.created_at %></p>
		<p><%= link_to "Edit Profile", '/users/edit' %></p>
	</div>
	<div>
		<% if @user.access_points.count > 0  %>
			<p>Has individual access to</p>
			<table class="table table-striped table-hover">
				<% @user.access_points.each do |access_point| %>
					<tr>
						<td><%= access_point.itemid %></td>
						<td><%= access_point.commentaryid %></td>
						<% if current_user.admin? %>
							<td>
								<%= form_for(:access_point, url: delete_access_point_path, method: :delete) do |f| %>
								<%= f.hidden_field :itemid, value: access_point.itemid %>
								<%= f.hidden_field :commentaryid, value: access_point.commentaryid %>
								<%= f.submit "Remove" %>
							<% end %>
						</td>
					<% end %>
					</tr>
				<% end %>
			</table>
		<% end %>
	</div>
	<div>
	<% if @user.access_requests.count > 0  %>
		<p>Has open requests for </p>
		<table class="table table-striped table-hover">
			<% @user.access_requests.each do |access_request| %>
				<% if access_request.open? %>
					<tr>
						<td><%= access_request.itemid %></td>
						<td><%= access_request.commentaryid %></td>
						<% if current_user.admin? %>
							<td>
								<%= form_for(:access_point, url: create_access_point_path(access_request.user.id), method: :post) do |f| %>
								<%= f.hidden_field :itemid, value: access_request.itemid %>
								<%= f.hidden_field :commentaryid, value: access_request.commentaryid %>
								<%= f.submit "Add Access Point" %>
								<% end %>
							</td>
						<% end %>
					</tr>
				<% end %>
			<% end %>
		</table>
	<% end %>
	</div>
	<% if current_user.admin? %>
		<div style="border-top: 1px solid black">
			<h3>Admin Options</h3>
			
			<div style="margin: 10px; border-top: 1px dotted gray;">
				<%= form_for(:access_point, url: create_access_point_path, method: :post) do |f| %>
					<p>Add Access Point</p>
					<%= f.text_field :itemid %>
					<%= f.text_field :commentaryid %>
					<%= f.submit "Add Access Point" %>
				<% end %>
			</div>
			<div style="margin: 10px; border-top: 1px dotted gray;">
				<%= form_for(:profile, url: :update_users_profile, method: :put) do |f| %>
				<p>Change User Role</p>
				  <%= f.text_field :role, autocomplete: "off" %>
				  <%= f.submit "Update User" %>
				<% end %>
				<br /><br />
				  <%= link_to "Back to Profiles List", users_profiles_path %>
			</div>
		</div>
	<% end %>
</div>
		