config/routes.rb
Rails.application.routes.draw do
  
  resources :access_requests

  root 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions", profiles: "users/profiles"}
  
  get 'posts/list' => 'posts#list'
  resources :posts
  
  resources :comments, except: [:new]

  resources :settings
  

  get 'articles/:articleid' => 'articles#show', as: :show_article
  get 'articles' => 'articles#index', as: :articles
  
  get 'biography' => 'pages#biography'
  get 'bibliography' => 'pages#bibliography' 

  get "comments/new/:itemid(/:pid)" => 'comments#new', as: :new_comment
  get "comments/list/:itemid(/:pid)" => 'comments#list', as: :list_comments
  
  get "index" => 'indices/indices#index'
  
  get "index/names/list(/:category)" => 'indices/names#list'
  get "index/names/show(/:nameid)" => 'indices/names#show'
  get "index/names/categories" => 'indices/names#categories'
  
  get "index/titles/list(/:category)" => 'indices/titles#list'
  get "index/titles/show(/:titleid)" => 'indices/titles#show'
  get "index/titles/categories" => 'indices/titles#categories'

  get "index/quotes/list(/:category)" => 'indices/quotes#list'
  get "index/quotes/show(/:quoteid)" => 'indices/quotes#show'
  get "index/quotes/categories" => 'indices/quotes#categories'

scope 'paragraphs' do
  get 'index' => 'paragraphs#index'
  get 'info' => 'paragraphs#info'
  get 'plaintext' => 'paragraphs#plaintext'
  get 'show2' => 'paragraphs#show2'

  get 'collation/:itemid/:pid' => 'paragraphs#collation', as: :paragraphs_collation
  get 'xml/:itemid/:pid(/:msslug)' => 'paragraphs#xml', as: :paragraphs_xml
  get 'json/:itemid/:pid(/:msslug)' => 'paragraphs#json', as: :paragraphs_json
  get 'variants/:itemid/:pid' => 'paragraphs#variants', as: :paragraphs_variants
  get 'notes/:itemid/:pid' => 'paragraphs#notes', as: :paragraphs_notes
  
  get ':itemid/:pid(/:msslug)' => 'paragraphs#show'
end
  
  get 'paragraphexemplar/json/:itemid/:pid' => 'paragraphexemplar#json'

  get 'permissions' => 'pages#permissions'
  
  get 'search' => 'search#show', as: :show_search

scope "text" do
  get '' => 'text#index'
  get 'draft_permissions/:itemid' => 'text#draft_permissions'
  get 'questions' => 'text#questions'
  get 'info/:itemid' => 'text#info'
  get 'status/:itemid' => 'text#status'
  get 'toc/:itemid(:/msslug)' => 'text#toc'
  get 'xml/:itemid(:/msslug)' => 'text#xml'
  get ':itemid(/:msslug)' => 'text#show', as: :show_text
end 

  get 'paragraphimage/showfoliozoom/:msslug/:canvas_id' => 'paragraphimage#showfoliozoom'
  get 'paragraphimage/showzoom/:itemid/:msslug/:pid' => 'paragraphimage#showzoom'
  get 'paragraphimage/:itemid/:msslug/:pid' => 'paragraphimage#show'

  
  get 'users/profiles/:id' => 'users/profiles#show', as: :users_profile
  delete 'users/profiles/:id' => 'users/profiles#destroy', as: :destroy_users_profile
  put 'users/profiles/:id' => 'users/profiles#update', as: :update_users_profile
  post 'users/profiles' => 'users/profiles#create', as: :create_users_profile
  get 'users/profiles' => 'users/profiles#index'

  get 'accesspoints/:commentaryid/:itemid' => 'access_points#show', as: :access_point
  post 'accesspoints/:id' => 'access_points#create', as: :create_access_point
  delete 'accesspoints/:id' => 'access_points#destroy', as: :delete_access_point
  

  

  

  

end

app/models/setting.rb
class Setting < ActiveRecord::Base
	attr_reader :confighash
	serialize :properties, JSON
  has_many :articles, dependent: :destroy
  after_initialize :set_confighash


  private
	  def set_confighash()
	  	# can't figure out how to get self.projectfildir
	  	# but its not causing an error because a lot of stuff in the config hash is not actually needed
	  	projectfiledir = "test"
				@confighash = {
					local_texts_dir: "#{Rails.root}/projectfiles/#{projectfiledir}/textfiles/", 
						citation_lists_dir: "#{Rails.root}/projectfiles/#{projectfiledir}/citationlists/", 
						xslt_dirs: { "default" => {
							critical: "#{Rails.root}/xslt/default/critical/",
							documentary: "#{Rails.root}/xslt/default/documentary/", 
							main_view: "main_view.xsl",
							index_view: "text_display_index.xsl", 
							clean_view: "clean_view.xsl",
							plain_text: "plaintext.xsl",
							json: "LbpToJson.xsl", 
							toc: "toc.xsl"
							}
						},
					git_repo: "bitbucket.org/jeffreycwitt/",
					git_username: ENV["GUN"],
					git_password: ENV["GPW"]
				}
	end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@settings = Setting.all
		#binding.pry @settings
    authorize @settings
	end
	def show
		if params[:id] == "current"
			@setting = Setting.find_by(commentaryid: @config.commentaryid)
		else
			@setting = Setting.find(params[:id])
		end
		authorize @setting
	end
	def edit
		
 		@setting = Setting.find(params[:id])
		authorize @setting
	end
	def update
		@setting = Setting.find(params[:id])
		authorize @setting
		if @setting.update(setting_params)
			redirect_to settings_path, :notice => "Setting successfully updated"
		else
			render 'edit'
		end

	end
	
	private 
		
		def setting_params
	  	
	  	
	  	
	  	#here I'm making sure these value get set as booleans.
	  	params[:setting][:blog] = to_boolean(params[:setting][:blog])
	  	params[:setting][:images] = to_boolean(params[:setting][:images])
	  	params[:setting][:properties] = eval(params[:setting][:properties])
	  
	  	params.require(:setting).permit!
	  end
		
		# a simple function to return a "true" "false" string as a boolean value
		
		def to_boolean(str)
		  str.downcase == 'true'
		end

end

app/views/settings/edit.html.erb
<div class="container">
  <h1>Editing Setting</h1>

  <%= form_for :setting, url: setting_path(@setting), method: :patch do |f| %>
   
    <% if @setting.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@setting.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @setting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
   <% @setting.attributes.each do |key, value| %>
    <p>
      <% #check to see if value is boolean 
      if [true, false].include? value %>
        <%= f.label key %><br/>
        <%= f.text_field key, value: value %><br/>
      <% else  %>
        <%= f.label key %><br/>
        <%= f.text_field key %><br/>
      <% end %>
    </p>
    <% end %>
    <button type="submit" class="btn btn-default">submit</button>
    <% end %>
   
  <%= link_to 'Settings List', settings_path %>
</div>

app/views/settings/index.html.erb
<div class="container">
	<h1>Settings</h1>
	<% @settings.each do |setting| %>
		<div id="#<%= setting.commentaryid %>">
			<p><strong><%= setting.commentaryid %></strong></p>
			<p><%= link_to "edit", edit_setting_path(setting.id) %> </p>
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						<td>Key</td>
						<td>Value</td>
					</tr>
				</thead>
				<tbody>
				<% setting.attributes.each do |key, value| %>
					<tr>
						<td><%= key %></td>
						<td><%= value %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	<% end %>
</div>

app/views/settings/show.html.erb
<div class="container">
	<h1>Setting</h1>
	<div id="#<%= @setting.commentaryid %>">
		<p><strong><%= @setting.commentaryid %></strong></p>
		<p><%= link_to "edit", edit_setting_path(@setting.id) %> </p>
		<table class="table table-striped table-hover">
			<thead>
				<tr>
					<td>Key</td>
					<td>Value</td>
				</tr>
			</thead>
			<tbody>
			<% @setting.attributes.each do |key, value| %>
				<tr>
					<td><%= key %></td>
					<td><%= value %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>